# Generated by Django 5.2.5 on 2025-10-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_film_kinopoisk_id_film_rating_alter_film_imdb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
